name: Deploy Blazor to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore FarhanS.Portfolio/FarhanS.Portfolio.sln
      
    - name: Build
      run: dotnet build FarhanS.Portfolio/FarhanS.Portfolio.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test FarhanS.Portfolio/FarhanS.Portfolio.sln --no-build --configuration Release --verbosity normal
      
    - name: Publish
      run: dotnet publish FarhanS.Portfolio/src/Web/FarhanS.Portfolio.csproj --no-build --configuration Release --output ./publish
      
    - name: Update base href for GitHub Pages
      run: |
        # Copy the GitHub Pages specific index.html
        cp FarhanS.Portfolio/src/Web/wwwroot/index.github.html ./publish/wwwroot/index.html
        
    - name: Add .nojekyll file
      run: touch ./publish/wwwroot/.nojekyll
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './publish/wwwroot'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
